### ISSUE TITLE
Any chance of updating this to tauri v2

### ISSUE THREAD

**Issue by ZelCloud** [dieharders/example-tauri-python-server-sidecar#1]
Upgrade to tauri v2?

**Comment by dieharders** [comment]
Yes, I have another project that I think I will be moving to Tauri. I dont have ETA, but likely before end of year.

**Comment by starascendin** [comment]
thannks

**Comment by dieharders** [comment]
Good news I have just published a new example for Tauri v2: https://github.com/dieharders/example-tauri-v2-python-server-sidecar

Cheers!
